"use strict";
// Auto-generated by generate-tests.js — do not edit manually.
// Cases derived by running ESLint+espree oracle against synthetic snippets.
const { RuleTester } = require("eslint");
const rule = require("../../node_modules/eslint-plugin-sonarjs").rules["function-name"];

const ruleTester = new RuleTester({ languageOptions: { ecmaVersion: 2022 } });
// Pass short name (without prefix) — the differential runner prepends "sonarjs/" automatically.
ruleTester.run("function-name", rule, {
  valid: [
    { code: "if (a) { if (b) { foo(); } }" },
    { code: "if (a && b) { foo(); }" },
    { code: "switch(x) { case 1: foo(); case 2: bar(); }" },
  ],
  invalid: [
    { code: "function MyFunc() {}" },
  ],
});
